### ISSUE TITLE
spelling errors in JULY-AUG edition 2023 

### ISSUE THREAD

**Issue by marwahavanshika** [tripathics/technodaya#2]
* academic spelling in the first heading.
*  difference in two spellings of programs.
<img width="368" alt="image" src="https://github.com/tripathics/technodaya/assets/101502532/1701fcb5-3205-4cee-860d-02c6c59b548b">

<img width="425" alt="image" src="https://github.com/tripathics/technodaya/assets/101502532/5664b477-c409-466a-9c8f-c398a944d4fc">

**Comment by tripathics** [comment]
Errors in content of magazine is due to mistakes committed while drafting the magazine. It can be fixed by correcting the content in the database.
